# Server Port
server.port=8081

# Application Name
spring.application.name=greet-service

# Eureka Client Configuration
# The URL where Eureka Server is running and listening for client registrations
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
# Prefer using IP address instead of hostname when registering with Eureka
eureka.instance.prefer-ip-address=true

# Actuator configuration for monitoring
management.endpoints.web.exposure.include=health,info
