# Port on which Eureka Server will run (default is 8761)
server.port=8761

# Indicate that this is the Eureka server itself, so it shouldn't register with itself
eureka.client.register-with-eureka=false

# Indicate that this server does not need to fetch the registry from other Eureka nodes
eureka.client.fetch-registry=false

# Configure logging for eureka server to be neat and tidy
logging.level.org.springframework.cloud.netflix.eureka=INFO
