# Port on which the API Gateway runs
server.port=9090

# Application Name
spring.application.name=api-gateway

# Eureka Registry Server Location
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable Gateway to automatically create routes using services registered on Eureka Server
spring.cloud.gateway.discovery.locator.enabled=true

# Force the locator to match service names in lower-case (e.g. greet-service instead of GREET-SERVICE)
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Expose Actuator Gateway endpoints for runtime management
management.endpoints.web.exposure.include=health,info,gateway

# Control Logging levels
logging.level.com.example.gateway=DEBUG
logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.web.reactive=INFO
